# Generated by Django 4.0.6 on 2022-07-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.framework')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.language')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.library')),
            ],
        ),
    ]
